DROP DATABASE IF EXISTS SISTEMA_HOSPITALAR;
CREATE DATABASE SISTEMA_HOSPITALAR;
USE SISTEMA_HOSPITALAR;

-- Endereço {Integer codigo (PK), String logradouro - String numero - String bairro - String CEP}
CREATE TABLE ENDERECO(
	CODIGO INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
	LOGRADOURO VARCHAR(40) NOT NULL,
	BAIRRO VARCHAR(100) NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	CEP VARCHAR(15) NOT NULL
);

-- Pessoa {String CPF, String nome - Date dataNascimento, Integer codigo, Integer codigo_endereco  (FK)}
CREATE TABLE PESSOA(
	CODIGO INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
  NOME VARCHAR (70) NOT NULL,
  DATA_NASCIMENTO DATE,
  CODIGO_ENDERECO INTEGER,
  CPF VARCHAR(15) NOT NULL,
	CONSTRAINT PESSOA_ENDERECO_PK FOREIGN KEY (CODIGO_ENDERECO) REFERENCES ENDERECO (CODIGO)
);

-- Plano {Integer codigo (PK) - String nome - double mensalidade}
CREATE TABLE PLANO(
	CODIGO INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
	NOME VARCHAR(70),
	MENSALIDADE DECIMAL(6,2)
);

-- Paciente {Integer codigo_plano (FK), Integer codigo_pessoa (FK e PK)}
CREATE TABLE PACIENTE(
	CODIGO_PESSOA INTEGER NOT NULL PRIMARY KEY,
	CODIGO_PLANO INTEGER,
  STATUS INTEGER NOT NULL,
	CONSTRAINT PACIENTE_PESSOA_PK FOREIGN KEY (CODIGO_PESSOA) REFERENCES PESSOA (CODIGO),
	CONSTRAINT PACIENTE_PLANO_PK FOREIGN KEY (CODIGO_PLANO) REFERENCES PLANO (CODIGO)
);

-- Medico {int CRM - double valorHora,  Integer codigo_pessoa (FK e PK)}
CREATE TABLE MEDICO(
	CODIGO INTEGER NOT NULL PRIMARY KEY,
	CRM VARCHAR(15) NOT NULL,
	VALOR_HORA DECIMAL(6,2),

	CONSTRAINT MEDICO_PESSOA_PK FOREIGN KEY (CODIGO) REFERENCES PESSOA (CODIGO)
);

-- Especialidade - String nome, Integer codigo (PK)
CREATE TABLE ESPECIALIDADE(
	CODIGO INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
	NOME VARCHAR(30) NOT NULL
);

-- Medico_Especialidade - Integer codigo_especialidade (FK) – Integer codigo_medico (FK)
CREATE TABLE MEDICO_ESPECIALIDADE(
	CODIGO_MEDICO INTEGER NOT NULL,
	CODIGO_ESPECIALIDADE INTEGER NOT NULL,

	CONSTRAINT MEDICO_ESPECIALIDADE_M_FK FOREIGN KEY (CODIGO_MEDICO) REFERENCES MEDICO (CODIGO),
	CONSTRAINT MEDICO_ESPECIALIDADE_E_FK FOREIGN KEY (CODIGO_ESPECIALIDADE) REFERENCES ESPECIALIDADE (CODIGO),
	CONSTRAINT MEDICO_ESPECIALIDADE_PK PRIMARY KEY (CODIGO_MEDICO, CODIGO_ESPECIALIDADE)
);

-- Sala - String nome, Integer codigo
CREATE TABLE SALA(
	CODIGO INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL
);

-- Procedimento -  Integer codigo_paciente (FK), Date data – Integer codigo_sala (FK) - String observacoes - double valor - int tempoDuracao
CREATE TABLE PROCEDIMENTO(
	CODIGO INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  CODIGO_PACIENTE INTEGER NOT NULL,
  DATA DATE,
  CODIGO_SALA INTEGER,
	OBSERVACOES VARCHAR(300),
  VALOR DECIMAL(6,2),
  TEMPO_DURACAO INTEGER,

	CONSTRAINT PROCEDIMENTO_PACIENTE_FK FOREIGN KEY (CODIGO_PACIENTE) REFERENCES PACIENTE (CODIGO_PESSOA),
  CONSTRAINT PROCEDIMENTO_SALA_FK FOREIGN KEY (CODIGO_SALA) REFERENCES SALA (CODIGO)
);

-- Medico_Procedimento -  Integer codigo_procedimento (FK) – Integer codigo_medico (FK)
CREATE TABLE MEDICO_PROCEDIMENTO(
  CODIGO_MEDICO INTEGER NOT NULL,
  CODIGO_PROCEDIMENTO INTEGER NOT NULL,

  CONSTRAINT MEDICO_PROCEDIMENTO_M_FK FOREIGN KEY (CODIGO_MEDICO) REFERENCES MEDICO (CODIGO),
  CONSTRAINT MEDICO_PROCEDIMENTO_FK FOREIGN KEY (CODIGO_PROCEDIMENTO) REFERENCES PROCEDIMENTO (CODIGO),
  CONSTRAINT MEDICO_PROCEDIMENTO_PK PRIMARY KEY (CODIGO_MEDICO, CODIGO_PROCEDIMENTO)
);

-- Consulta – Integer codigo_paciente (FK) – Integer codigo_medico (FK) - Date data - String receituario - double valor, Integer codigo (PK)
CREATE TABLE CONSULTA(
	CODIGO INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  CODIGO_MEDICO INTEGER NOT NULL,
  CODIGO_PACIENTE INTEGER NOT NULL,
  DATA DATE,
  RECEITUARIO VARCHAR (200),
  VALOR DECIMAL(6,2),

  CONSTRAINT CONSULTA_MEDICO_FK FOREIGN KEY (CODIGO_MEDICO) REFERENCES MEDICO (CODIGO),
  CONSTRAINT CONSULTA_PACIENTE_FK FOREIGN KEY (CODIGO_PACIENTE) REFERENCES PACIENTE (CODIGO_PESSOA)
);
